<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0CCPETD" failures="1" tests="6" name="com.crm.reqing.SampleTest.RetrySampleTest" time="48.548" errors="0" timestamp="2022-07-08T15:44:13 IST" skipped="4">
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="allone" time="8.970">
    <skipped/>
  </testcase> <!-- allone -->
  <system-out/>
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="allone" time="7.758">
    <skipped/>
  </testcase> <!-- allone -->
  <system-out/>
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="allone" time="8.062">
    <skipped/>
  </testcase> <!-- allone -->
  <system-out/>
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="alltwo" time="7.770"/>
  <system-out/>
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="allone" time="7.732">
    <skipped/>
  </testcase> <!-- allone -->
  <system-out/>
  <testcase classname="com.crm.reqing.SampleTest.RetrySampleTest" name="allone" time="8.256">
    <failure message="" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at com.crm.reqing.SampleTest.RetrySampleTest.allone(RetrySampleTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- allone -->
  <system-out/>
</testsuite> <!-- com.crm.reqing.SampleTest.RetrySampleTest -->
